import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { AnalysisResult } from "../types";

export function generatePdfReport(result: AnalysisResult, contractLabel?: string): void {
  const doc = new jsPDF();
  const title = contractLabel || "Contract Analysis Report";
  const date = new Date().toLocaleString();

  doc.setFontSize(20);
  doc.text("LexGuard AI Risk Report", 14, 22);
  
  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text(`Document: ${title}`, 14, 32);
  doc.text(`Date: ${date}`, 14, 38);
  
  doc.setLineWidth(0.5);
  doc.setDrawColor(200, 200, 200);
  doc.line(14, 42, 196, 42);

  // Summary section
  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text("Summary", 14, 52);
  
  doc.setFontSize(12);
  doc.text(`Overall Risk: ${result.overallRisk.toUpperCase()}`, 14, 60);
  doc.text(`Risk Score: ${result.riskScore}/100`, 14, 68);
  doc.text(`Confidence: ${result.confidence}%`, 14, 76);
  doc.text(`Categories: ${result.riskCategories.join(", ")}`, 14, 84);

  let startY = 94;

  // Risky Clauses
  if (result.riskyClauses && result.riskyClauses.length > 0) {
    doc.setFontSize(14);
    doc.text("Risky Clauses", 14, startY);
    startY += 6;
    
    const clauseData = result.riskyClauses.map(c => [
      c.severity.toUpperCase(),
      c.title,
      c.excerpt,
      c.explanation
    ]);

    autoTable(doc, {
      startY: startY,
      head: [["Severity", "Title", "Clause Text", "AI Explanation"]],
      body: clauseData,
      theme: 'grid',
      headStyles: { fillColor: [41, 128, 185] },
      columnStyles: {
        0: { cellWidth: 25 },
        1: { cellWidth: 35 },
        2: { cellWidth: 70 },
        3: { cellWidth: 50 },
      },
      styles: { fontSize: 10, cellPadding: 3, overflow: 'linebreak' },
    });
    
    startY = (doc as any).lastAutoTable.finalY + 15;
  }

  // Recommendations
  if (result.recommendations && result.recommendations.length > 0) {
    doc.setFontSize(14);
    doc.text("Recommendations", 14, startY);
    startY += 6;

    const recData = result.recommendations.map(r => [
      r.priority.toUpperCase(),
      r.title,
      r.description
    ]);

    autoTable(doc, {
      startY: startY,
      head: [["Priority", "Recommendation", "Details"]],
      body: recData,
      theme: 'grid',
      headStyles: { fillColor: [39, 174, 96] },
      columnStyles: {
        0: { cellWidth: 25 },
        1: { cellWidth: 45 },
        2: { cellWidth: 110 },
      },
      styles: { fontSize: 10, cellPadding: 3, overflow: 'linebreak' },
    });
    
    startY = (doc as any).lastAutoTable.finalY + 15;
  }

  // Legal Disclaimer
  doc.setFontSize(10);
  doc.setTextColor(150);
  const disclaimer = "Disclaimer: This report is generated by an AI (LexGuard AI) and is intended for informational purposes only. It does not constitute legal advice. Always consult with a qualified attorney for legal matters.";
  const splitDisclaimer = doc.splitTextToSize(disclaimer, 182);
  
  if (startY + (splitDisclaimer.length * 5) > 280) {
    doc.addPage();
    startY = 20;
  }
  doc.text(splitDisclaimer, 14, startY);

  doc.save(`lexguard-risk-report-${new Date().toISOString().slice(0, 10)}.pdf`);
}
